import highRidgeLookout from '@/assets/concepts/map-location/high-ridge-lookout.png'
import minervaMap from '@/assets/concepts/map-location/minerva-map-concept.png'
import mistLakeDock from '@/assets/concepts/map-location/mist-lake-dock.png'
import rangerCamp from '@/assets/concepts/map-location/ranger-camp.png'
import willowwindLibrary from '@/assets/concepts/map-location/willowwind-library.png'

export const MAP_BACKGROUND = minervaMap

export const MAP_LOCATIONS = [
  {
    id: 'ranger-camp',
    name: '巡林官营地',
    region: '溪谷原野',
    x: 31,
    y: 61,
    summary: '每一次巡林都从这里出发。',
    description:
      '溪流在营地旁分成两条道路。这里保存着你的地图、苗木清单，以及那些仍在等待被理解的方向。',
    requirements: {},
    prerequisites: [],
    adjacent: ['old-forest-gate', 'mist-lake-dock'],
    defaultUnlocked: true,
    sceneImage: rangerCamp,
    sceneAlt: '溪流旁的巡林官木屋、帐篷和林间营地水彩场景',
    accent: '#6f8c70',
    order: 0,
  },
  {
    id: 'old-forest-gate',
    name: '古老林门',
    region: '杉木边界',
    x: 19,
    y: 45,
    summary: '被旧杉木守住的第一道林门。',
    description:
      '没有真正的围墙，只有两株年长杉木与一段被脚步磨亮的石径。跨过它，地图便第一次向外展开。',
    requirements: { t1: 1 },
    prerequisites: ['ranger-camp'],
    adjacent: ['ranger-camp', 'moss-stone-courtyard', 'moonlit-ruins'],
    defaultUnlocked: false,
    sceneImage: null,
    sceneAlt: '古老杉木与石径组成的林门占位场景',
    accent: '#71856b',
    order: 1,
  },
  {
    id: 'mist-lake-dock',
    name: '雾湖栈桥',
    region: '北方水域',
    x: 68,
    y: 43,
    summary: '薄雾停留在湖面，木舟等待下一次出发。',
    description:
      '旧栈桥伸进安静的水面，远山在雾里只剩下柔和轮廓。这里提醒巡林官：方向有时要在停顿后才会显现。',
    requirements: { t1: 3 },
    prerequisites: ['ranger-camp'],
    adjacent: ['ranger-camp', 'willowwind-library', 'high-ridge-lookout'],
    defaultUnlocked: false,
    sceneImage: mistLakeDock,
    sceneAlt: '薄雾湖面、木栈桥和小舟的水彩场景',
    accent: '#7299a6',
    order: 2,
  },
  {
    id: 'moss-stone-courtyard',
    name: '苔石庭院',
    region: '溪谷原野',
    x: 43,
    y: 72,
    summary: '散落石块围成的安静庭院。',
    description:
      '溪流与小路在这里交会。石面上的苔藓记录了缓慢发生的变化，也给尚未命名的行动留出一块空地。',
    requirements: { t1: 5 },
    prerequisites: ['old-forest-gate'],
    adjacent: ['old-forest-gate', 'willowwind-library', 'golden-harbor'],
    defaultUnlocked: false,
    sceneImage: null,
    sceneAlt: '溪流交会处的苔石庭院占位场景',
    accent: '#9aa679',
    order: 3,
  },
  {
    id: 'willowwind-library',
    name: '柳风书库',
    region: '南岸柳原',
    x: 72,
    y: 73,
    summary: '柳树环抱着一间向风敞开的书库。',
    description: '书页、麦穗与河风在这里相遇。书库收藏的不是标准答案，而是一次次实践后留下的观察。',
    requirements: { t1: 8, t2: 1 },
    prerequisites: ['mist-lake-dock', 'moss-stone-courtyard'],
    prerequisiteMode: 'any',
    adjacent: ['mist-lake-dock', 'moss-stone-courtyard', 'golden-harbor'],
    defaultUnlocked: false,
    sceneImage: willowwindLibrary,
    sceneAlt: '柳树、溪流与开放书架环绕的水彩书库场景',
    accent: '#a2a86f',
    order: 4,
  },
  {
    id: 'high-ridge-lookout',
    name: '高岭瞭望台',
    region: '北境群山',
    x: 81,
    y: 20,
    summary: '从高处回望走过的河谷与森林。',
    description:
      '山风穿过木制瞭望台，河流在远处变成一条明亮的线。抵达这里并不是征服，而是获得重新判断方向的距离。',
    requirements: { t1: 8, t3: 1 },
    prerequisites: ['mist-lake-dock'],
    adjacent: ['mist-lake-dock', 'golden-harbor'],
    defaultUnlocked: false,
    sceneImage: highRidgeLookout,
    sceneAlt: '俯瞰河谷群山的木制高岭瞭望台水彩场景',
    accent: '#8193a0',
    order: 5,
  },
  {
    id: 'moonlit-ruins',
    name: '月辉遗迹',
    region: '杉木边界',
    x: 12,
    y: 27,
    summary: '月光照见林线深处尚未读懂的石迹。',
    description:
      '残存的石墙没有说明自己曾经是什么。它只在夜色中提供一个可以安静停留、重新解释旧经验的位置。',
    requirements: { t2: 6, t4: 1 },
    prerequisites: ['old-forest-gate', 'willowwind-library'],
    prerequisiteMode: 'all',
    adjacent: ['old-forest-gate', 'willowwind-library'],
    defaultUnlocked: false,
    sceneImage: null,
    sceneAlt: '月光下的森林石墙遗迹占位场景',
    accent: '#7b8197',
    order: 6,
  },
  {
    id: 'golden-harbor',
    name: '黄金港湾',
    region: '远行海岸',
    x: 88,
    y: 83,
    summary: '河流在这里汇入更辽阔的水面。',
    description:
      '港湾保留着长期贡献留下的木栈道与灯火。它不是旅程的终点，而是一处能够看见更多去向的开放边界。',
    requirements: { t3: 8, t5: 1 },
    prerequisites: ['high-ridge-lookout', 'willowwind-library'],
    prerequisiteMode: 'all',
    adjacent: ['moss-stone-courtyard', 'willowwind-library', 'high-ridge-lookout'],
    defaultUnlocked: false,
    sceneImage: null,
    sceneAlt: '河海交汇处的木栈道港湾占位场景',
    accent: '#c39d55',
    order: 7,
  },
]

export const MAP_LOCATION_BY_ID = Object.fromEntries(
  MAP_LOCATIONS.map((location) => [location.id, location]),
)
